#!/usr/bin/python
#coding: UTF-8

from sys import argv
from optparse import OptionParser
from subprocess import call
from os.path import realpath, dirname, join

parser = OptionParser()
parser.add_option('-n', '--name', dest='name', type='string', help='Project, virtualenv name. \
                   Also used in virtualenv --promt=NAME. Required. ', metavar='NAME')

(options, args) = parser.parse_args()

if options.name is None:
    parser.error('--name=NAME is required! Use run.py --help')

DIR_PATH = dirname(realpath(__file__))
ENV = join(DIR_PATH, 'env.sh')
call('%s %s' % (ENV, options.name), shell=True)