#!/bin/bash

# Catalogs tree
WEBAPPS=/webapps
TEMPLATES=$WORKON_HOME/templates
PROJECT_TEMPLATE=$WORKON_HOME/project_template
MAINAPP=mainapp
if [ -f $WORKON_HOME/name ]; then
    PROJECT_NAME=$(cat $WORKON_HOME/name)
else
    PROJECT_NAME=$@
fi
PROJECT_DIR=$WEBAPPS/django/$PROJECT_NAME
SERVER=$WEBAPPS/server/$PROJECT_NAME
STATIC=$WEBAPPS/django/static/$PROJECT_NAME
STATIC_SRC=$PROJECT_DIR/$MAINAPP/static_src
MEDIA=$WEBAPPS/django/media/$PROJECT_NAME
INTERNAL=$WEBAPPS/django/internal/$PROJECT_NAME
SETTINGS=$MAINAPP/settings
BOOTSTRAP_SED=$PROJECT_DIR/libs/bootstrap/less/
UWSGI_PARAMS=$WEBAPPS/server/uwsgi_params
DUMMY_ROOT=$WEBAPPS/dummy/$PROJECT_NAME
LIBS=libs

GIT_SUBMODULES=$PROJECT_DIR/_submodules.cfg.sh
PIP_PACKAGES=$PROJECT_DIR/_packages.cfg.pip
