#!/bin/bash
# This hook is run before a virtualenv is deleted.

# sudo required for settings up nginx and uwsgi
sudo echo 'Enter sudo passwrod please:'

sudo rm /etc/uwsgi/vassals/$@.ini
sudo rm /etc/nginx/sites-enabled/$@.conf

sudo service nginx restart

rm -rf /webapps/django/$@
rm -rf /webapps/django/static/$@
rm -rf /webapps/django/media/$@
rm -rf /webapps/django/internal/$@
rm -rf /webapps/server/$@

# drop db
if [ ! -f $HOME/.pgpass ]; then
    printf '\nYou can touch .pgpass file with chmode 0600 in your home dir\n'
    printf "insted prompt password for user $PG_SU every time.\n"
    printf 'Read the man: http://www.postgresql.org/docs/9.0/static/libpq-pgpass.html\n\n'
fi
# PostgreSQL
read -p "Enter PostgreSQL superuser (default: postgres)? " PG_SU
if [[ $PG_SU == '' ]]; then
    PG_SU=postgres
fi
read -p "Enter DB host (default: localhost)? " PG_HOST
if [[ $PG_HOST == '' ]]; then
    PG_HOST=localhost
fi
source $WORKON_HOME/_config.sh
psql -h $PG_HOST -U $PG_SU -f $TEMPLATES/dropdb.sql -v user=$@
# sudo -u postgres dropdb $@
# sudo -u postgres dropuser $@
