#!/bin/bash
# This hook is run before a virtualenv is deleted.

echo '*** Stop uWSGI ***'
sudo $HOME/webapps/$@/bin/uwsgi --stop $HOME/webapps/$@/var/log/uwsgi/$@.log
echo '*** rm uWSGI from rc ***'
rm $HOME/webapps/uwsgiauto/$@.sh
echo '*** rm NGINX config ***'
sudo rm /etc/nginx/sites-enabled/$@_nginx.conf
echo '*** restart NGINX ***'
sudo service nginx restart
