#!/bin/bash
# This hook is run before a virtualenv is deleted.

sudo rm /etc/uwsgi/vassals/$@.ini
sudo rm /etc/nginx/sites-enabled/$@.conf

sudo service nginx restart

rm -rf /webapps/django/$@
rm -rf /webapps/server/$@

# postgres passwrod:
printf '\nEnter postgres passwrod please(twice)\n'
sudo -u postgres dropdb $@
sudo -u postgres dropuser $@
